MvcEfCore/Controllers/DatVeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcEfCore.Data;
using MvcEfCore.Models;
using MvcEfCore.ViewModels;
using Newtonsoft.Json;

namespace MvcEfCore.Controllers
{
    
    
    public class DatVeController : Controller
    {
        
        public int giaChuyenBay = 0;
        private readonly ApplicationDbContext _context;
        public List<LichChuyenBayVM> chuyenBayVM;
        // GET: DatVe
        public DatVeController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var ChuyenBay = _context.LichChuyenBays.ToList();
            chuyenBayVM = new List<LichChuyenBayVM>();
            int dem = 0;
            foreach (var chuyenBay in ChuyenBay)
            {
                chuyenBayVM.Add(new LichChuyenBayVM()
                {
                    ChuyenBayID = chuyenBay.ChuyenBayID,
                    GiaVe = chuyenBay.GiaVe,
                    NgayGioBay = chuyenBay.NgayGioBay,
                    ThoiGianBay = chuyenBay.ThoiGianBay,
                });

                var ghe01 = _context.PhieuDatVes.Where(p => p.ChuyenBayID == chuyenBay.ChuyenBayID && p.HangID == "HA01");
                if ((ghe01 == null || ghe01.Count() == 0) && chuyenBayVM[dem].BusinessClass == 0)
                {
                    chuyenBayVM[dem].BusinessClass = chuyenBay.BusinessClass;
                }
                else chuyenBayVM[dem].BusinessClass = chuyenBay.BusinessClass - ghe01.Count();

                var ghe02 = _context.PhieuDatVes.Where(p => p.ChuyenBayID == chuyenBay.ChuyenBayID && p.HangID == "HA02");
                if ((ghe02 == null || ghe02.Count() == 0) && chuyenBayVM[dem].BusinessClass == 0)
                {
                    chuyenBayVM[dem].EconomyClass = chuyenBay.EconomyClass;
                }
                else chuyenBayVM[dem].EconomyClass = chuyenBay.EconomyClass - ghe02.Count();

                var datCho01 = _context.PhieuDatChos.Where(p => p.ChuyenBayID == chuyenBay.ChuyenBayID && p.HangID == "HA01");
                if ((datCho01 == null || datCho01.Count() == 0) &&  chuyenBayVM[dem].BusinessClass == 0)
                {
                    chuyenBayVM[dem].EconomyClass = chuyenBay.BusinessClass;
                }
                else chuyenBayVM[dem].EconomyClass = chuyenBayVM[dem].BusinessClass - datCho01.Count();

                var datCho02 = _context.PhieuDatChos.Where(p => p.ChuyenBayID == chuyenBay.ChuyenBayID && p.HangID == "HA02");
                if (datCho02 == null || datCho02.Count() == 0)
                {
                    //chuyenBayVM[dem].SoGheHang2 = chuyenBay.SoGheHang2;
                }
                else chuyenBayVM[dem].EconomyClass = chuyenBayVM[dem].EconomyClass - datCho02.Count();
                dem++;
            }
            return View(chuyenBayVM);
        }

        // GET: DatVe/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DatVe/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DatVe/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DatVe/Delete/5
        public IActionResult Delete(int id)
        {

            return View();
        }
        public async Task<IActionResult> Create(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lichChuyenBays = await _context.LichChuyenBays.FindAsync(id);
            if (lichChuyenBays == null)
            {
                return NotFound();
            }

            ViewBag.IdChuyenBay = id;
            giaChuyenBay = lichChuyenBays.GiaVe;
            ViewBag.GiaVe = lichChuyenBays.GiaVe;
            ViewBag.HangVe = _context.HangVes.ToList();
            ViewBag.GiaVeHang01 = _context.HangVes.Where(p => p.HangID == "HA01").SingleOrDefault().TiLeGia * lichChuyenBays.GiaVe / 100 + lichChuyenBays.GiaVe;

            ViewData["HangID"] = new SelectList(_context.HangVes, "HangID", "HangID");
            ViewData["KhachHangID"] = new SelectList(_context.KhachHangs, "KhachHangID", "KhachHangID");
            //ViewData["ChuyenBayID"] = new SelectList(_context.LichChuyenBays, "ChuyenBayID", "ChuyenBayID");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
                            Create(
                            [Bind("PhieuDatVeID,KhachHangId,HangID,ChuyenBayID")] PhieuDatVe phieuDatVe,
                            KhachHang KhachHang)
        {
            if (ModelState.IsValid)
            {
                KhachHang.KhachHangID = phieuDatVe.ChuyenBayID + KhachHang.CMND;
                _context.Add(KhachHang);
                await _context.SaveChangesAsync();
                var x = _context.LichChuyenBays.SingleOrDefault(p => p.ChuyenBayID == phieuDatVe.ChuyenBayID).GiaVe;
                phieuDatVe.KhachHangID = phieuDatVe.ChuyenBayID + KhachHang.CMND;
                phieuDatVe.GiaTien = _context.HangVes.SingleOrDefault(p => p.HangID == phieuDatVe.HangID).TiLeGia * x / 100 + x;
                _context.Add(phieuDatVe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HangID"] = new SelectList(_context.HangVes, "HangID", "HangID", phieuDatVe.HangID);
            ViewData["KhachHangID"] = new SelectList(_context.KhachHangs, "KhachHangID", "KhachHangID", phieuDatVe.KhachHangID);
            ViewData["ChuyenBayID"] = new SelectList(_context.LichChuyenBays, "ChuyenBayID", "ChuyenBayID", phieuDatVe.ChuyenBayID);
            return View(phieuDatVe);
        }
        // POST: DatVe/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> Create2(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lichChuyenBays = await _context.LichChuyenBays.FindAsync(id);
            if (lichChuyenBays == null)
            {
                return NotFound();
            }

            ViewBag.IdChuyenBay = id;
            giaChuyenBay = lichChuyenBays.GiaVe;
            ViewBag.GiaVe = lichChuyenBays.GiaVe;
            ViewBag.HangVe = _context.HangVes.ToList();
            ViewBag.GiaVeHang01 = _context.HangVes.Where(p => p.HangID == "HA01").SingleOrDefault().TiLeGia * lichChuyenBays.GiaVe / 100 + lichChuyenBays.GiaVe;

            ViewData["HangID"] = new SelectList(_context.HangVes, "HangID", "HangID");
            ViewData["KhachHangID"] = new SelectList(_context.KhachHangs, "KhachHangID", "KhachHangID");
            //ViewData["ChuyenBayID"] = new SelectList(_context.LichChuyenBays, "ChuyenBayID", "ChuyenBayID");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
                            Create2(
                            [Bind("PhieuDatChoId,KhachHangId,HangID,ChuyenBayID")] PhieuDatCho phieuDatCho,
                            KhachHang KhachHang)
        {
            if (ModelState.IsValid)
            {
                KhachHang.KhachHangID = phieuDatCho.ChuyenBayID + KhachHang.CMND;
                _context.Add(KhachHang);
                await _context.SaveChangesAsync();
                var x = _context.LichChuyenBays.SingleOrDefault(p => p.ChuyenBayID == phieuDatCho.ChuyenBayID).GiaVe;
                phieuDatCho.KhachHangID = phieuDatCho.ChuyenBayID + KhachHang.CMND;
                phieuDatCho.GiaTien = _context.HangVes.SingleOrDefault(p => p.HangID == phieuDatCho.HangID).TiLeGia * x / 100 + x;
                _context.Add(phieuDatCho);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HangID"] = new SelectList(_context.HangVes, "HangID", "HangID", phieuDatCho.HangID);
            ViewData["KhachHangID"] = new SelectList(_context.KhachHangs, "KhachHangID", "KhachHangID", phieuDatCho.KhachHangID);
            ViewData["ChuyenBayID"] = new SelectList(_context.LichChuyenBays, "ChuyenBayID", "ChuyenBayID", phieuDatCho.ChuyenBayID);
            return View(phieuDatCho);
        }
        // POST: DatVe/Delete/5
       
        //public async Task<IActionResult> XemGiaVe(string id)
        //{
        //    var x = _context.HangVes.SingleOrDefault(p => p.HangID == id).TiLeGia;
        //    ViewBag.GiaTien = x * ViewBag.GiaChuyenBay + ViewBag.GiaChuyenBay;
        //    return View();
        //}

        // POST: PhieuDatVes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> XemGiaVe()
        //{
        //    return View();
        //}
        [HttpPost]
        public JsonResult Update([FromBody] HangId model)
        {

MvcEfCore/Views/Shared/AccountDropDown.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<a class="nav-link dropdown-toggle" id="navbarDropdown" style="color:orange" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Hello, @(User.Identity.Name ?? "User")!
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
    @if (!SignInManager.IsSignedIn(User))
    {
        <a asp-action="Login" asp-controller="Account" class="dropdown-item">Log in</a>
        <a asp-action="Register" asp-controller="Account" class="dropdown-item">Register</a>
    }
    else
    {
        <form method="post" asp-action="logout" asp-controller="account" class="no-padding-margin dropdown-item">
            <button asp-action="logout" asp-controller="Account" class="btn dropdown-item btn-no-effect">Log out</button>
            <button class="dropdown-item" asp-area="Admin" asp-controller="AdminHome" asp-action="Index">Management</button>
        </form>

        if (User.IsInRole("Admin"))
        {
            <button class="dropdown-item" asp-area="Admin" asp-controller="AdminHome" asp-action="Index">Management</button>
        }
        else
        {
            
        }
    }
</div>

MvcEfCore/Views/Shared/MyPage.cshtml
@{
    Layout = "~/Areas/Admin/Views/Share/_AdminLayout.cshtml";

}

MvcEfCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>DreamAirTicket</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/aos.css">
    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">

    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">

    

    @section Scripts{
        <script>
            // This is the "Offline page" service worker

            // Add this below content to your HTML page, or add the js file to your page at the very top to register service worker

            // Check compatibility for the browser we're running this in
            if ("serviceWorker" in navigator) {
                if (navigator.serviceWorker.controller) {
                    console.log("[PWA Builder] active service worker found, no need to register");
                } else {
                    // Register the service worker
                    navigator.serviceWorker
                        .register("pwabuilder-sw.js", {
                            scope: "~/"
                        })
                        .then(function (reg) {
                            console.log("[PWA Builder] Service worker has been registered for scope: " + reg.scope);
                        });
                }
            }

        </script>
    }
    
</head>
<body>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="/home">DreamAirTicket</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>
            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="/Home" class="nav-link">Home Page</a></li>
                    <li class="nav-item"><a asp-controller="DatVe" asp-action="Index" class="nav-link">Booking</a></li>
                    <li class="nav-item"><a href="/Home/Contact" class="nav-link">Contact Us</a></li>
                </ul>
                <div class="nav-item dropdown">
                   <partial name="AccountDropDown"/>
                </div>
                @*<div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            </ul>

        </div>*@
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    @RenderBody()
    <div class="container body-content">

        <!--Footer-->

    </div>
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <h4 class="title">DreamAirTicket</h4>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><a href="#">155 Su Van Hanh Street, Ward 12, District 10, HCMC</a></li>
                            <li><a href="#">Tel: +84 325 999 999</a></li>
                            <li><a href="#">Mail: ariticket@gmail.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    
                </div>
                <div class="col-sm-3">
                    <h4 class="title">More Information</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">About Us</a></li>
                        <li><a href="#" class="py-2 d-block">Online enquiry</a></li>
                        <li><a href="#" class="py-2 d-block">Call Us</a></li>
                        <li><a href="#" class="py-2 d-block">General enquiries</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h4 class="title">Contact Us</h4>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                    <ul class="payment">
                        <li><a href="#"><i class="fa fa-cc-amex" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-credit-card" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-paypal" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-visa" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>


    </footer>
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>
    @RenderSection("css", required: false)
    @RenderSection("Scripts", required: false)
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/jquery.timepicker.min.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/js/google-map.js"></script>
    <script src="~/js/main.js"></script>

</body>
</html>
 

MvcEfCore/Views/Shared/_TableView.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@RenderBody()
@section css {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
}
@section Scripts {
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable();
        });
    </script>
}